const ROWS=5000000;
const pages=["Executive Overview","Import Analytics","Export Analytics","Shipment Control Tower","Customs & Clearance","Freight & Cost Analytics","CHA / Forwarder Performance","Delay & RCA","Supplier Analytics","Data Explorer","Reports & Downloads"];
const countries=["South Korea","China","Vietnam","Japan","Thailand","UAE","Germany","USA","Singapore"];
const ports=["ICD Dadri","Delhi Air Cargo","JNPT","Mundra","Chennai","Mumbai Air Cargo","ICD Tughlakabad"];
const suppliers=["Seoul Components","Hanoi Display Tech","Shenzhen PCB","Osaka Motors","Bangkok Plastics","Busan Semiconductor","Frankfurt Controls"];
const chas=["Apex Customs","TransClear India","Gateway CHA","Prime Exim"];
const forwarders=["DHL Global Forwarding","Kuehne+Nagel","DSV","DB Schenker","Maersk Logistics"];
const materials=["Display Panels","Compressors","PCB","Semiconductors","Plastic Components","Motors","Packaging","Spare Parts"];
const reasons=["Documentation Issue","Vessel Delay","Port Congestion","Customs Hold","CHA Delay","Supplier Delay","Incorrect HS Code","Internal Approval"];
let current=pages[0],page=0;
function rng(n,s=1){let x=Math.sin((n+1)*12.9898+s*78.233)*43758.5453;return x-Math.floor(x)}
function pick(a,n,s){return a[Math.floor(rng(n,s)*a.length)]}
function dateFor(n,s=2){const now=new Date(),days=Math.floor(rng(n,s)*730);return new Date(now.getTime()-days*86400000)}
function money(v){return "₹"+Intl.NumberFormat("en-IN",{notation:"compact",maximumFractionDigits:1}).format(v)}
function row(n){
 const imp=rng(n,3)>.28, mode=rng(n,4)>.28?"Sea":"Air", d=dateFor(n), delay=rng(n,8)<.14?Math.ceil(rng(n,9)*14):0;
 const val=Math.round((180000+rng(n,5)*9800000)/100)*100, freight=Math.round(val*(mode==="Air"?.045:.014)*(0.8+rng(n,6)*.5));
 const duty=Math.round(val*(.075+rng(n,7)*.105)), status=delay>0?"Delayed":pick(["Cleared","Cleared","In Transit","Customs Pending"],n,11);
 return {Shipment_ID:"LGX-"+String(n+1).padStart(7,"0"),Shipment_Type:imp?"Import":"Export",Date:d.toISOString().slice(0,10),Supplier:pick(suppliers,n,12),Origin_Country:imp?pick(countries,n,13):"India",Destination_Country:imp?"India":pick(countries,n,14),Port:pick(ports,n,15),Mode:mode,Material:pick(materials,n,16),CHA:pick(chas,n,17),Forwarder:pick(forwarders,n,18),Shipment_Value:val,Freight_Cost:freight,Customs_Duty:duty,Clearance_TAT:1+Math.floor(rng(n,19)*4)+Math.min(delay,5),Status:status,Delay_Days:delay,Delay_Reason:delay?pick(reasons,n,20):"—",Risk:delay>7?"Critical":delay?"Attention":"On Track"};
}
document.querySelector("#nav").innerHTML=pages.map((p,i)=>`<button data-p="${p}" class="${i===0?"active":""}">${p}</button>`).join("");
document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{current=b.dataset.p;page=0;document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelector("#pageTitle").textContent=current+" · Greater Noida";render()});

function kpis(type="all"){let mult=+document.querySelector("#period").value/24;let vals=[["Total Shipments",Intl.NumberFormat("en-IN").format(Math.round(ROWS*mult)),"🚢"],["Trade Value",money(184000000000*mult),"₹"],["On-Time %","91.6%","✓"],["Avg Clearance","3.2 days","⏱"],["Freight Cost",money(3280000000*mult),"✈"],["Customs Duty",money(14700000000*mult),"▣"]];return `<div class="kpis">${vals.map((x,i)=>`<div class="card k${i}"><div class="kicon">${x[2]}</div><small>${x[0]}</small><h2>${x[1]}</h2><span class="up">▲ vs previous period</span></div>`).join("")}</div>`}
function chartCard(title,type,labels,vals){const id="c"+Math.random().toString(36).slice(2);setTimeout(()=>drawChart(id,type,labels,vals),0);return `<div class="panel chartpanel"><div class="charttitle"><h3>${title}</h3><span>Interactive</span></div><canvas id="${id}" height="240"></canvas></div>`}
function drawChart(id,type,labels,vals){const el=document.getElementById(id);if(!el)return;new Chart(el,{type,data:{labels,datasets:[{data:vals,label:"Value",borderWidth:2,tension:.35,fill:type==="line",backgroundColor:type==="doughnut"?["#a50034","#d52b63","#6b0f32","#e5a2b9","#7b7b86","#bfc0c5"]:"rgba(165,0,52,.16)",borderColor:"#a50034"}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==="doughnut",position:"bottom"}},scales:type==="doughnut"?{}:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:"#f0f0f2"}}}}})}
function chartsFor(pageName){const months=["Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct"];const trend=months.map((_,i)=>Math.round(310000+rng(i,41)*150000));const cost=months.map((_,i)=>Math.round(180+rng(i,42)*120));const common=chartCard("Shipment Volume Trend","line",months,trend)+chartCard("Mode Mix","doughnut",["Sea","Air"],[72,28])+chartCard("Top Ports","bar",["ICD Dadri","JNPT","Mundra","Delhi Air","Chennai"],[91,76,68,54,47])+chartCard("Trade Value Trend","line",months,cost);if(pageName==="Customs & Clearance")return chartCard("Clearance TAT by Port","bar",["Dadri","JNPT","Mundra","Delhi Air","Chennai"],[3.8,2.6,2.9,2.1,3.2])+chartCard("Customs Status","doughnut",["Cleared","Pending","Hold","Query"],[74,14,7,5])+common;if(pageName==="Freight & Cost Analytics")return chartCard("Freight Cost Trend","line",months,cost)+chartCard("Cost by Mode","doughnut",["Sea","Air","Other"],[54,42,4])+chartCard("Cost by Forwarder","bar",["DHL","K+N","DSV","DB Schenker","Maersk"],[88,81,72,69,64])+chartCard("Cost Variance %","bar",["Korea","China","Vietnam","Japan","Thailand"],[6,12,-3,8,4]);if(pageName==="Delay & RCA")return chartCard("Delay Reasons","bar",["Docs","Vessel","Congestion","Customs","CHA","Supplier"],[32,22,16,13,10,7])+chartCard("Risk Mix","doughnut",["On Track","Attention","Critical"],[78,16,6])+chartCard("Delay Trend","line",months,[8,9,7,11,10,8,12,9,7,8,6,7])+chartCard("Delay by Port","bar",["Dadri","JNPT","Mundra","Delhi Air","Chennai"],[14,9,8,6,11]);return common}
function table(title="Operational Shipment Detail"){let start=page*12;let rs=Array.from({length:12},(_,i)=>row(start+i));return `<div class="panel tablewrap compact"><div class="datahead"><div><h3>${title}</h3><span class="note">Detailed drill-down · 5M-row virtual analytical layer</span></div><button onclick="downloadExtract()">Download CSV</button></div><table><thead><tr>${["Shipment ID","Type","Date","Port","Mode","Value","Status","Delay","Risk"].map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rs.map(r=>`<tr><td>${r.Shipment_ID}</td><td>${r.Shipment_Type}</td><td>${r.Date}</td><td>${r.Port}</td><td>${r.Mode}</td><td>${money(r.Shipment_Value)}</td><td><span class="pill">${r.Status}</span></td><td>${r.Delay_Days}d</td><td>${r.Risk}</td></tr>`).join("")}</tbody></table><div class="pages"><span>Drill-down rows ${start+1}–${start+12}</span><div><button onclick="page=Math.max(0,page-1);render()">←</button> <button onclick="page++;render()">→</button></div></div></div>`}
function overview(){return kpis()+`<div class="chartgrid">${chartsFor("Executive Overview")}</div><div class="insightStrip"><div><b>⚠ Customs Aging</b><span>ICD Dadri 18% above target</span></div><div><b>📄 Documentation RCA</b><span>32% of current delays</span></div><div><b>✈ Freight Exception</b><span>Air cost +14% vs 3M avg</span></div></div>`}
function analytic(){return kpis()+`<div class="chartgrid">${chartsFor(current)}</div>`+(current==="Shipment Control Tower"?table(current+" Drill-down"):"")}
function dataExplorer(){return `<div class="panel"><div class="datahead"><div><h3>Enterprise Data Explorer</h3><p class="note">Each analytical domain represents 5,000,000 synthetic rows spanning the last 24 months. Data is generated deterministically on demand rather than storing multi-GB files in GitHub.</p></div><button onclick="downloadExtract()">Download 100K CSV</button></div><div class="kpis">${["Shipments","Customs","Freight","CHA / Forwarder","Supplier / Delay"].map(x=>`<div class="card"><small>${x}</small><h2>5,000,000</h2><span class="up">Last 24 months</span></div>`).join("")}</div></div>`+table("Shipment Data Preview")}
function reports(){return `<div class="panel"><h3>Reports & Downloads</h3><p class="note">Generate practical browser-safe extracts from the 5M-row synthetic analytical model.</p><div class="alerts">${["Daily EXIM Report","Delayed Shipment Report","Customs Pending Report","Freight Cost Report","CHA Performance Report","Management Summary"].map(x=>`<div class="alert"><b>${x}</b><br><button onclick="downloadExtract()">Download CSV Extract</button></div>`).join("")}</div></div>`}
function render(){document.querySelector("#content").innerHTML=current==="Executive Overview"?overview():current==="Data Explorer"?dataExplorer():current==="Reports & Downloads"?reports():analytic()}
function resetFilters(){document.querySelector("#period").value="24";document.querySelector("#mode").value="All Modes";document.querySelector("#status").value="All Status";render()}
function downloadExtract(){const count=100000,keys=Object.keys(row(0));let parts=[keys.join(",")+"\n"];for(let i=0;i<count;i++){let r=row(i);parts.push(keys.map(k=>String(r[k]).replaceAll(","," ")).join(",")+"\n")}let blob=new Blob(parts,{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="lg_exim_100k_synthetic_extract.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
render();