const ROWS=5000000;
const pages=["Executive Overview","Import Analytics","Export Analytics","Shipment Control Tower","Customs & Clearance","Freight & Cost Analytics","CHA / Forwarder Performance","Delay & RCA","Supplier Analytics","Data Explorer","Reports & Downloads"];
const countries=["South Korea","China","Vietnam","Japan","Thailand","UAE","Germany","USA","Singapore"];
const ports=["ICD Dadri","Delhi Air Cargo","JNPT","Mundra","Chennai","Mumbai Air Cargo","ICD Tughlakabad"];
const suppliers=["Seoul Components","Hanoi Display Tech","Shenzhen PCB","Osaka Motors","Bangkok Plastics","Busan Semiconductor","Frankfurt Controls"];
const chas=["Apex Customs","TransClear India","Gateway CHA","Prime Exim"];
const forwarders=["DHL Global Forwarding","Kuehne+Nagel","DSV","DB Schenker","Maersk Logistics"];
const materials=["Display Panels","Compressors","PCB","Semiconductors","Plastic Components","Motors","Packaging","Spare Parts"];
const reasons=["Documentation Issue","Vessel Delay","Port Congestion","Customs Hold","CHA Delay","Supplier Delay","Incorrect HS Code","Internal Approval"];
let current=pages[0],page=0;
function rng(n,s=1){let x=Math.sin((n+1)*12.9898+s*78.233)*43758.5453;return x-Math.floor(x)}
function pick(a,n,s){return a[Math.floor(rng(n,s)*a.length)]}
function dateFor(n,s=2){const now=new Date(),days=Math.floor(rng(n,s)*730);return new Date(now.getTime()-days*86400000)}
function money(v){return "₹"+Intl.NumberFormat("en-IN",{notation:"compact",maximumFractionDigits:1}).format(v)}
function row(n){
 const imp=rng(n,3)>.28, mode=rng(n,4)>.28?"Sea":"Air", d=dateFor(n), delay=rng(n,8)<.14?Math.ceil(rng(n,9)*14):0;
 const val=Math.round((180000+rng(n,5)*9800000)/100)*100, freight=Math.round(val*(mode==="Air"?.045:.014)*(0.8+rng(n,6)*.5));
 const duty=Math.round(val*(.075+rng(n,7)*.105)), status=delay>0?"Delayed":pick(["Cleared","Cleared","In Transit","Customs Pending"],n,11);
 return {Shipment_ID:"LGX-"+String(n+1).padStart(7,"0"),Shipment_Type:imp?"Import":"Export",Date:d.toISOString().slice(0,10),Supplier:pick(suppliers,n,12),Origin_Country:imp?pick(countries,n,13):"India",Destination_Country:imp?"India":pick(countries,n,14),Port:pick(ports,n,15),Mode:mode,Material:pick(materials,n,16),CHA:pick(chas,n,17),Forwarder:pick(forwarders,n,18),Shipment_Value:val,Freight_Cost:freight,Customs_Duty:duty,Clearance_TAT:1+Math.floor(rng(n,19)*4)+Math.min(delay,5),Status:status,Delay_Days:delay,Delay_Reason:delay?pick(reasons,n,20):"—",Risk:delay>7?"Critical":delay?"Attention":"On Track"};
}
document.querySelector("#nav").innerHTML=pages.map((p,i)=>`<button data-p="${p}" class="${i===0?"active":""}">${p}</button>`).join("");
document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{current=b.dataset.p;page=0;document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelector("#pageTitle").textContent=current+" · Greater Noida";render()});

function kpis(type="all"){let mult=+document.querySelector("#period").value/24;let vals=[["Total Shipments",Intl.NumberFormat("en-IN").format(Math.round(ROWS*mult)),"🚢"],["Trade Value",money(184000000000*mult),"₹"],["On-Time %","91.6%","✓"],["Avg Clearance","3.2 days","⏱"],["Freight Cost",money(3280000000*mult),"✈"],["Customs Duty",money(14700000000*mult),"▣"]];return `<div class="kpis">${vals.map((x,i)=>`<div class="card k${i}"><div class="kicon">${x[2]}</div><small>${x[0]}</small><h2>${x[1]}</h2><span class="up">▲ vs previous period</span></div>`).join("")}</div>`}
function chartCard(title,type,labels,vals,cls="",opts={}){const id="c"+Math.random().toString(36).slice(2);setTimeout(()=>drawChart(id,type,labels,vals,opts),0);return `<div class="panel chartpanel ${cls}"><div class="charttitle"><h3>${title}</h3><span>● LIVE VIEW</span></div><canvas id="${id}"></canvas></div>`}
function drawChart(id,type,labels,vals,opts={}){const el=document.getElementById(id);if(!el)return;const pal=["#a50034","#e33d73","#ffb547","#3ca6ff","#38c79f","#8b78ff","#f06aa6"];new Chart(el,{type,data:{labels,datasets:[{data:vals,label:opts.label||"Value",borderWidth:2,tension:.35,fill:type==="line",backgroundColor:type==="doughnut"?pal:"rgba(165,0,52,.20)",borderColor:type==="doughnut"?pal:"#d51b5a",borderRadius:6}]},options:{indexAxis:opts.horizontal?"y":"x",responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==="doughnut",position:"right",labels:{color:"#5c6370",boxWidth:10}},tooltip:{enabled:true}},scales:type==="doughnut"?{}:{x:{ticks:{color:"#737987"},grid:{display:false}},y:{ticks:{color:"#737987"},grid:{color:"#edf0f3"}}}}})}
function metricStrip(items){return `<div class="metricStrip">${items.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]||""}</small></div>`).join("")}</div>`}
function pageCharts(name){const m=["Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct"], vol=[318,342,335,376,361,398,407,389,421,436,418,452], val=[12.1,13.4,12.8,15.2,14.7,16.3,17.1,16.6,18.4,19.2,18.7,20.1];
if(name==="Executive Overview")return `<div class="vizgrid">${chartCard("Shipment Volume & Trade Trend","line",m,vol,"wide",{label:"Shipments"})}${chartCard("Shipment Status","doughnut",["Cleared","In Transit","Pending","Delayed"],[62,20,10,8],"donut")}${chartCard("Top Origin Countries","bar",["South Korea","China","Vietnam","Japan","Thailand"],[94,82,66,51,39],"",{horizontal:true})}${chartCard("Port-wise Shipments","bar",["ICD Dadri","JNPT","Mundra","Delhi Air","Chennai"],[92,77,68,55,43])}${chartCard("Material Mix","doughnut",["Panels","Compressors","PCB","Semi-conductors","Motors"],[31,24,18,16,11],"donut")}${chartCard("Monthly Trade Value (₹ Cr)","line",m,val,"wide")}</div>`;
if(name==="Import Analytics")return metricStrip([["Import Share","72%","of shipments"],["Import Value","₹132.5B","+8.4% YoY"],["Top Origin","South Korea","28% share"],["Avg Lead Time","18.4 d","-1.2 d"]])+`<div class="vizgrid">${chartCard("Import Value Trend","line",m,val,"wide")}${chartCard("Import by Origin","doughnut",["Korea","China","Vietnam","Japan","Thailand"],[28,24,19,16,13])}${chartCard("Imports by Material","bar",["Panels","Compressors","PCB","Semiconductor","Motors"],[98,82,70,61,48], "",{horizontal:true})}${chartCard("Port of Entry","bar",["Dadri","JNPT","Mundra","Delhi Air","Chennai"],[88,74,63,52,41])}</div>`;
if(name==="Export Analytics")return metricStrip([["Export Share","28%","of shipments"],["Export Value","₹51.5B","+11.2% YoY"],["Top Market","UAE","21% share"],["Avg Dispatch","1.8 d","within SLA"]])+`<div class="vizgrid">${chartCard("Export Value Trend","line",m,[4.1,4.4,4.2,4.8,4.6,5.1,5.4,5.0,5.7,5.9,5.6,6.2],"wide")}${chartCard("Destination Mix","doughnut",["UAE","USA","Germany","Singapore","Thailand"],[21,19,18,16,12])}${chartCard("Export by Product","bar",["Finished Goods","Spares","Panels","Components","Accessories"],[89,71,58,46,37],"",{horizontal:true})}${chartCard("Dispatch Performance","bar",["On Time","<1d Late","1-3d Late",">3d Late"],[91,5,3,1])}</div>`;
if(name==="Customs & Clearance")return metricStrip([["Avg Clearance","3.2 d","target 3.0"],["Pending","10.4%","↓ 1.1%"],["Duty","₹14.7B","24M"],["Queries","2.8%","of BOE"]])+`<div class="vizgrid">${chartCard("Clearance TAT by Port","bar",["Dadri","JNPT","Mundra","Delhi Air","Chennai"],[3.8,2.6,2.9,2.1,3.2],"wide")}${chartCard("Customs Status","doughnut",["Cleared","Pending","Hold","Query"],[74,14,7,5])}${chartCard("Pending Aging Bucket","bar",["0-1d","2-3d","4-5d","6-7d",">7d"],[42,29,16,8,5])}${chartCard("Duty Trend (₹ Cr)","line",m,[52,57,55,61,59,65,68,64,70,74,71,76])}</div>`;
if(name==="Freight & Cost Analytics")return metricStrip([["Freight Cost","₹3.28B","+4.1%"],["Cost / Shipment","₹656","-2.3%"],["Air Cost Share","42%","28% volume"],["Saving Opp.","₹218M","identified"]])+`<div class="vizgrid">${chartCard("Freight Cost Trend","line",m,[180,194,188,211,205,226,239,231,248,262,254,271],"wide")}${chartCard("Cost by Mode","doughnut",["Sea","Air","Other"],[54,42,4])}${chartCard("Forwarder Cost Index","bar",["DHL","K+N","DSV","DB Schenker","Maersk"],[88,81,72,69,64],"",{horizontal:true})}${chartCard("Lane Cost Variance %","bar",["Korea","China","Vietnam","Japan","Thailand"],[6,12,-3,8,4])}</div>`;
if(name==="CHA / Forwarder Performance")return metricStrip([["Best CHA","Apex","96% SLA"],["Best Forwarder","DHL","94% SLA"],["Avg CHA TAT","2.7 d","-0.3 d"],["Exceptions","4.6%","↓ 0.8%"]])+`<div class="vizgrid">${chartCard("CHA SLA %","bar",["Apex","TransClear","Gateway","Prime"],[96,92,89,86],"wide")}${chartCard("Forwarder Share","doughnut",["DHL","K+N","DSV","DBS","Maersk"],[27,23,19,17,14])}${chartCard("Forwarder On-time %","bar",["DHL","K+N","DSV","DBS","Maersk"],[94,92,90,88,87])}${chartCard("Exception Trend","line",m,[7,6,6,5,7,5,4,5,4,4,5,4])}</div>`;
if(name==="Delay & RCA")return metricStrip([["Delayed","8.4%","of shipments"],["Critical", "6%","of delayed"],["Top Cause","Documents","32%"],["Cost at Risk","₹218M","action needed"]])+`<div class="vizgrid">${chartCard("Delay Reason Pareto","bar",["Documents","Vessel","Congestion","Customs","CHA","Supplier"],[32,22,16,13,10,7],"wide",{horizontal:true})}${chartCard("Risk Mix","doughnut",["On Track","Attention","Critical"],[78,16,6])}${chartCard("Delay Trend %","line",m,[8,9,7,11,10,8,12,9,7,8,6,7])}${chartCard("Delay by Port","bar",["Dadri","JNPT","Mundra","Delhi Air","Chennai"],[14,9,8,6,11])}</div>`;
if(name==="Supplier Analytics")return metricStrip([["Suppliers","7","active"],["Best OTD","Seoul Comp.","96%"],["Avg Lead Time","16.8 d","-0.9 d"],["At Risk","2","suppliers"]])+`<div class="vizgrid">${chartCard("Supplier On-time Delivery %","bar",["Seoul","Hanoi","Shenzhen","Osaka","Bangkok"],[96,93,90,88,84],"wide")}${chartCard("Supplier Share","doughnut",["Seoul","Hanoi","Shenzhen","Osaka","Bangkok"],[25,22,20,18,15])}${chartCard("Lead Time (Days)","bar",["Seoul","Hanoi","Shenzhen","Osaka","Bangkok"],[14,16,18,15,21])}${chartCard("Supplier Delay Trend","line",m,[8,7,9,6,8,7,5,6,5,4,6,5])}</div>`;
return `<div class="vizgrid">${chartCard("Shipment Trend","line",m,vol,"wide")}${chartCard("Status Mix","doughnut",["Cleared","Transit","Pending","Delayed"],[62,20,10,8])}</div>`}
function table(title="Operational Shipment Detail"){let start=page*12;let rs=Array.from({length:12},(_,i)=>row(start+i));return `<div class="panel tablewrap compact"><div class="datahead"><div><h3>${title}</h3><span class="note">Detailed drill-down · 5M-row virtual analytical layer</span></div><button onclick="downloadExtract()">Download CSV</button></div><table><thead><tr>${["Shipment ID","Type","Date","Port","Mode","Value","Status","Delay","Risk"].map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rs.map(r=>`<tr><td>${r.Shipment_ID}</td><td>${r.Shipment_Type}</td><td>${r.Date}</td><td>${r.Port}</td><td>${r.Mode}</td><td>${money(r.Shipment_Value)}</td><td><span class="pill">${r.Status}</span></td><td>${r.Delay_Days}d</td><td>${r.Risk}</td></tr>`).join("")}</tbody></table><div class="pages"><span>Drill-down rows ${start+1}–${start+12}</span><div><button onclick="page=Math.max(0,page-1);render()">←</button> <button onclick="page++;render()">→</button></div></div></div>`}
function overview(){return kpis()+pageCharts("Executive Overview")+`<div class="insightStrip"><div><b>Customs aging</b><span>ICD Dadri 18% above target</span></div><div><b>Documentation RCA</b><span>32% of current delays</span></div><div><b>Freight exception</b><span>Air cost +14% vs 3M avg</span></div></div>`}
function analytic(){if(current==="Shipment Control Tower")return kpis()+pageCharts(current)+table("Live Shipment Exceptions");return pageCharts(current)}
function dataExplorer(){return `<div class="panel"><div class="datahead"><div><h3>Enterprise Data Explorer</h3><p class="note">Each analytical domain represents 5,000,000 synthetic rows spanning the last 24 months. Data is generated deterministically on demand rather than storing multi-GB files in GitHub.</p></div><button onclick="downloadExtract()">Download 100K CSV</button></div><div class="kpis">${["Shipments","Customs","Freight","CHA / Forwarder","Supplier / Delay"].map(x=>`<div class="card"><small>${x}</small><h2>5,000,000</h2><span class="up">Last 24 months</span></div>`).join("")}</div></div>`+table("Shipment Data Preview")}
function reports(){return `<div class="panel"><h3>Reports & Downloads</h3><p class="note">Generate practical browser-safe extracts from the 5M-row synthetic analytical model.</p><div class="alerts">${["Daily EXIM Report","Delayed Shipment Report","Customs Pending Report","Freight Cost Report","CHA Performance Report","Management Summary"].map(x=>`<div class="alert"><b>${x}</b><br><button onclick="downloadExtract()">Download CSV Extract</button></div>`).join("")}</div></div>`}
function render(){document.querySelector("#content").innerHTML=current==="Executive Overview"?overview():current==="Data Explorer"?dataExplorer():current==="Reports & Downloads"?reports():analytic()}
function resetFilters(){document.querySelector("#period").value="24";document.querySelector("#mode").value="All Modes";document.querySelector("#status").value="All Status";render()}
function downloadExtract(){const count=100000,keys=Object.keys(row(0));let parts=[keys.join(",")+"\n"];for(let i=0;i<count;i++){let r=row(i);parts.push(keys.map(k=>String(r[k]).replaceAll(","," ")).join(",")+"\n")}let blob=new Blob(parts,{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="lg_exim_100k_synthetic_extract.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
render();