const ROWS=5000000;
const pages=["Executive Overview","Import Analytics","Export Analytics","Shipment Control Tower","Customs & Clearance","Freight & Cost Analytics","CHA / Forwarder Performance","Delay & RCA","Supplier Analytics","Data Explorer","Reports & Downloads"];
const countries=["South Korea","China","Vietnam","Japan","Thailand","UAE","Germany","USA","Singapore"];
const ports=["ICD Dadri","Delhi Air Cargo","JNPT","Mundra","Chennai","Mumbai Air Cargo","ICD Tughlakabad"];
const suppliers=["Seoul Components","Hanoi Display Tech","Shenzhen PCB","Osaka Motors","Bangkok Plastics","Busan Semiconductor","Frankfurt Controls"];
const chas=["Apex Customs","TransClear India","Gateway CHA","Prime Exim"];
const forwarders=["DHL Global Forwarding","Kuehne+Nagel","DSV","DB Schenker","Maersk Logistics"];
const materials=["Display Panels","Compressors","PCB","Semiconductors","Plastic Components","Motors","Packaging","Spare Parts"];
const reasons=["Documentation Issue","Vessel Delay","Port Congestion","Customs Hold","CHA Delay","Supplier Delay","Incorrect HS Code","Internal Approval"];
let current=pages[0],page=0;
function rng(n,s=1){let x=Math.sin((n+1)*12.9898+s*78.233)*43758.5453;return x-Math.floor(x)}
function pick(a,n,s){return a[Math.floor(rng(n,s)*a.length)]}
function dateFor(n,s=2){const now=new Date(),days=Math.floor(rng(n,s)*730);return new Date(now.getTime()-days*86400000)}
function money(v){return "₹"+Intl.NumberFormat("en-IN",{notation:"compact",maximumFractionDigits:1}).format(v)}
function row(n){
 const imp=rng(n,3)>.28, mode=rng(n,4)>.28?"Sea":"Air", d=dateFor(n), delay=rng(n,8)<.14?Math.ceil(rng(n,9)*14):0;
 const val=Math.round((180000+rng(n,5)*9800000)/100)*100, freight=Math.round(val*(mode==="Air"?.045:.014)*(0.8+rng(n,6)*.5));
 const duty=Math.round(val*(.075+rng(n,7)*.105)), status=delay>0?"Delayed":pick(["Cleared","Cleared","In Transit","Customs Pending"],n,11);
 return {Shipment_ID:"LGX-"+String(n+1).padStart(7,"0"),Shipment_Type:imp?"Import":"Export",Date:d.toISOString().slice(0,10),Supplier:pick(suppliers,n,12),Origin_Country:imp?pick(countries,n,13):"India",Destination_Country:imp?"India":pick(countries,n,14),Port:pick(ports,n,15),Mode:mode,Material:pick(materials,n,16),CHA:pick(chas,n,17),Forwarder:pick(forwarders,n,18),Shipment_Value:val,Freight_Cost:freight,Customs_Duty:duty,Clearance_TAT:1+Math.floor(rng(n,19)*4)+Math.min(delay,5),Status:status,Delay_Days:delay,Delay_Reason:delay?pick(reasons,n,20):"—",Risk:delay>7?"Critical":delay?"Attention":"On Track"};
}
document.querySelector("#nav").innerHTML=pages.map((p,i)=>`<button data-p="${p}" class="${i===0?"active":""}">${p}</button>`).join("");
document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{current=b.dataset.p;page=0;document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelector("#pageTitle").textContent=current;render()});
document.querySelector("#menu").onclick=()=>document.querySelector(".shell").classList.toggle("open");
function kpis(type="all"){let mult=+document.querySelector("#period").value/24;return `<div class="kpis">
${[["Total Shipments",Intl.NumberFormat("en-IN").format(Math.round(ROWS*mult))],["Trade Value",money(184000000000*mult)],["On-Time %","91.6%"],["Avg Clearance TAT","3.2 days"],["Freight Cost",money(3280000000*mult)],["Customs Duty",money(14700000000*mult)],["Delayed Shipments",Intl.NumberFormat("en-IN").format(Math.round(ROWS*.084*mult))],["Cost at Risk",money(218000000*mult)]].map(x=>`<div class="card"><small>${x[0]}</small><h2>${x[1]}</h2><span class="up">↑ optimized vs prior period</span></div>`).join("")}</div>`}
function bars(){return `<div class="panel"><h3>24-Month Shipment Trend</h3><div class="bars">${Array.from({length:12},(_,i)=>`<div class="bar" style="height:${45+rng(i,31)*150}px"><i>${i+1}</i></div>`).join("")}</div></div>`}
function table(title="Operational Shipment Detail"){let start=page*25;let rs=Array.from({length:25},(_,i)=>row(start+i));return `<div class="panel tablewrap"><div class="datahead"><div><h3>${title}</h3><span class="note">Virtual dataset: ${ROWS.toLocaleString("en-IN")} deterministic synthetic records · rolling 24 months</span></div><button onclick="downloadExtract()">Download 100K CSV</button></div><table><thead><tr>${["Shipment ID","Type","Date","Origin","Port","Mode","Material","Value","CHA","Status","Delay","Risk"].map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rs.map(r=>`<tr><td>${r.Shipment_ID}</td><td>${r.Shipment_Type}</td><td>${r.Date}</td><td>${r.Origin_Country}</td><td>${r.Port}</td><td>${r.Mode}</td><td>${r.Material}</td><td>${money(r.Shipment_Value)}</td><td>${r.CHA}</td><td><span class="pill">${r.Status}</span></td><td>${r.Delay_Days}d</td><td>${r.Risk}</td></tr>`).join("")}</tbody></table><div class="pages"><span>Showing ${start+1}–${start+25} of ${ROWS.toLocaleString("en-IN")}</span><div><button onclick="page=Math.max(0,page-1);render()">←</button> <button onclick="page++;render()">→</button></div></div></div>`}
function overview(){return kpis()+`<div class="grid">${bars()}<div class="panel"><h3>Management Attention</h3><div class="alerts"><div class="alert"><b>Customs aging rising</b><br><small>ICD Dadri · 18% above target</small></div><div class="alert"><b>Documentation RCA</b><br><small>32% of current delays</small></div><div class="alert"><b>Freight exception</b><br><small>Air route cost +14% vs 3M avg</small></div><div class="alert"><b>Detention exposure</b><br><small>Critical shipments need action</small></div></div></div></div>`+table()}
function analytic(){let label=current;return kpis()+`<div class="grid">${bars()}<div class="panel"><h3>${label} Insights</h3><div class="alerts"><div class="alert"><b>Performance exception detected</b><br><small>Drill into the detail table for RCA.</small></div><div class="alert"><b>24-month comparison</b><br><small>Filters recalculate the analytical view.</small></div><div class="alert"><b>5M-row analytical layer</b><br><small>Generated on demand for browser performance.</small></div></div></div></div>`+table(label+" Detail")}
function dataExplorer(){return `<div class="panel"><div class="datahead"><div><h3>Enterprise Data Explorer</h3><p class="note">Each analytical domain represents 5,000,000 synthetic rows spanning the last 24 months. Data is generated deterministically on demand rather than storing multi-GB files in GitHub.</p></div><button onclick="downloadExtract()">Download 100K CSV</button></div><div class="kpis">${["Shipments","Customs","Freight","CHA / Forwarder","Supplier / Delay"].map(x=>`<div class="card"><small>${x}</small><h2>5,000,000</h2><span class="up">Last 24 months</span></div>`).join("")}</div></div>`+table("Shipment Data Preview")}
function reports(){return `<div class="panel"><h3>Reports & Downloads</h3><p class="note">Generate practical browser-safe extracts from the 5M-row synthetic analytical model.</p><div class="alerts">${["Daily EXIM Report","Delayed Shipment Report","Customs Pending Report","Freight Cost Report","CHA Performance Report","Management Summary"].map(x=>`<div class="alert"><b>${x}</b><br><button onclick="downloadExtract()">Download CSV Extract</button></div>`).join("")}</div></div>`}
function render(){document.querySelector("#content").innerHTML=current==="Executive Overview"?overview():current==="Data Explorer"?dataExplorer():current==="Reports & Downloads"?reports():analytic()}
function resetFilters(){document.querySelector("#period").value="24";document.querySelector("#mode").value="All Modes";document.querySelector("#status").value="All Status";render()}
function downloadExtract(){const count=100000,keys=Object.keys(row(0));let parts=[keys.join(",")+"\n"];for(let i=0;i<count;i++){let r=row(i);parts.push(keys.map(k=>String(r[k]).replaceAll(","," ")).join(",")+"\n")}let blob=new Blob(parts,{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="lg_exim_100k_synthetic_extract.csv";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
render();